apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mon-application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mon-application
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # si CPU > 50%, un nouveau pod sera créé
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
