apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 8080
        env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: sql-cm
              key: MYSQL_USER
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: sql-cm
              key: MYSQL_DATABASE
        - name: WORDPRESS_DB_HOST
          value: mysql.database.svc.cluster.local
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mon-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: wordpress-pv-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-pv-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
